[build-system]
requires = ["scikit-build-core", "pybind11==2.13.*", "wheel"]
build-backend = "scikit_build_core.build"

[project]
dependencies = [
    "Fiona >= 1.8.0, < 2.0.0",
    "affine",
    "geopandas >= 0.14.0, < 1.0.0",
    "laspy[lazrs] >= 2.3.0, < 3.0.0",
    "meshio >= 5.0.0, < 6.0.0",
    "numpy >= 1.20.0, < 3.0.0",
    "pillow >= 9.0.0, < 12.0.0",
    "protobuf >= 5.0.0, < 6.0.0",
    "psutil",
    "pyassimp",
    "pybind11",
    "pygltflib",
    "pypoints2grid >= 0.1.9",
    "pyproj >= 3.1.0, < 4.0.0",
    "rasterio >= 1.2.0, < 2.0.0",
    "rasterstats >= 0.19.0, < 1.0.0",
    "scipy >= 1.13.0, < 2.0.0",
    "shapely >= 2.0.0, < 3.0.0",
    "tqdm>=4.66.1",
]

version = "0.9.0dev"
name = "dtcc-core"
description = "DTCC Core"
readme = "README.md"
authors = [
    { name = "Anders Logg", email = "logg@chalmers.se" },
    { name = "Vasilis Naserentin", email = "vasilis.naserentin@chalmers.se" },
    { name = "Dag Wästberg", email = "dwastberg@gmail.com" },
    { name = "George Spaias", email = "gspaiasa@ece.auth.gr" },
    { name = "Jens Olsson", email = "jens.olsson@chalmersindustriteknik.se" },
]
requires-python = ">=3.10"
classifiers = [
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
test = ["pytest"]


[tool.scikit-build]
wheel.expand-macos-universal-tags = true
