# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtcc_test.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64tcc_test.proto\x12\tDTCC_TEST\".\n\x04\x43ity\x12&\n\tbuildings\x18\x01 \x03(\x0b\x32\x13.DTCC_TEST.Building\"<\n\x08\x42uilding\x12\n\n\x02id\x18\x01 \x01(\t\x12$\n\x08geometry\x18\x02 \x03(\x0b\x32\x12.DTCC_TEST.Surface\"\x1b\n\x07Surface\x12\x10\n\x08vertices\x18\x01 \x03(\x02\x42\x02H\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dtcc_test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_CITY']._serialized_start=30
  _globals['_CITY']._serialized_end=76
  _globals['_BUILDING']._serialized_start=78
  _globals['_BUILDING']._serialized_end=138
  _globals['_SURFACE']._serialized_start=140
  _globals['_SURFACE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
