#!/usr/bin/env bash

# Get the directory where the 'run-tests' script is stored
TESTS_DIR="$(cd "$(dirname "$0")" && pwd)"
echo "Script directory: $TESTS_DIR"

# Define the array
test_modules=("builder" "io" "model")

# Print each element (for verification)
for module in "${test_modules[@]}"; do
    echo "Running dtcc-$module Python tests"
    echo "======================================================================"
    python3 -m unittest discover -s "$TESTS_DIR/$module"
done
