#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROTO_DIR=$script_dir/../dtcc_core/schemas

PYTHON_DIR=$script_dir/../dtcc_core/model
echo "Building Python classes..."
protoc --python_out="$PYTHON_DIR" --proto_path="$PROTO_DIR" dtcc.proto
CPP_DIR=$script_dir/../dtcc_core/cpp/protobuf
mkdir -p "$CPP_DIR"
echo "Building C++ classes..."
protoc --cpp_out="$CPP_DIR" --proto_path="$PROTO_DIR" dtcc.proto
